[[redirects]]
from="/*"
to="/index.html"
status=200

[build]
  functions = "netlify/functions"  # Path to the functions directory

[[functions]]
  name = "pingServer"
  schedule = "*/5 * * * *"  # Runs every 5 minutes
